import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/Icon";

export const metadata: Metadata = { title: "Support", description: "Get product support and contact Devnet Limited." };

export default function SupportPage() {
  return <main><section className="support-hero"><div className="container support-hero-grid"><div data-reveal><span className="eyebrow">Devnet support</span><h1>Keep business-critical systems moving with a clear path to help.</h1><p>Use the support portal for existing cases or contact Devnet when you need help identifying the right support channel.</p><div className="hero-actions"><a className="button button-red" href="https://support.devnetlimited.com" target="_blank" rel="noreferrer">Open support portal <span>↗</span></a><Link className="button button-outline" href="/contact">Contact Devnet</Link></div></div><div className="support-console" data-reveal><div className="support-console-head"><span><i/>System support</span><b>Online</b></div><div className="support-ticket"><Icon name="headset"/><div><small>Step 1</small><strong>Describe the issue</strong><p>Product, environment, impact and urgency.</p></div></div><div className="support-line"/><div className="support-ticket"><Icon name="search"/><div><small>Step 2</small><strong>Review and diagnose</strong><p>Share evidence, logs and reproduction details.</p></div></div><div className="support-line"/><div className="support-ticket"><Icon name="check"/><div><small>Step 3</small><strong>Resolve and confirm</strong><p>Validate the fix and document the outcome.</p></div></div></div></div></section><section className="section support-options"><div className="container"><div className="section-heading split" data-reveal><div><span className="eyebrow">Choose the right route</span><h2>Support for active systems and new requirements.</h2></div><p>Provide enough context so the request reaches the right people quickly.</p></div><div className="support-option-grid">{[["headset","Existing product support","Use the dedicated support portal for incidents, known deployments and product questions.","Open portal","https://support.devnetlimited.com"],["message","General assistance","Email Devnet for non-urgent questions or help identifying a project or support contact.","Email support","mailto:info@devnetlimited.com"],["spark","Enhancement request","Discuss new workflow, integration, reporting or product requirements with the solutions team.","Start conversation","/contact"]].map(([icon,title,desc,label,href])=><a key={title} href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} data-reveal><span><Icon name={icon}/></span><h3>{title}</h3><p>{desc}</p><b>{label} →</b></a>)}</div></div></section></main>;
}
